INSERT INTO USER_ROLES ( NAME ) VALUES ('user');
INSERT INTO USER_ROLES ( NAME ) VALUES ('admin');

INSERT INTO USER_ACCOUNTS ( LOGIN , PASSWORD , EMAIL , FIRST_NAME , LAST_NAME , BIRTHDAY , ROLE_ID )
VALUES ( 'user', 'user', 'u@ser.net', 'John', 'Smith', '1980-01-01', '1');
INSERT INTO USER_ACCOUNTS ( LOGIN , PASSWORD , EMAIL , FIRST_NAME , LAST_NAME , BIRTHDAY , ROLE_ID ) 
VALUES ( 'admin', 'admin', 'a@dmin.net', 'Sarah', 'Connor', '1970-02-08', '2');
